# Cargar los datos
<hr>

In [2]:
import pandas as pd

In [6]:
import os
print(os.getcwd())

c:\Users\Eliud\Desktop\Proyecto tesis\Descriptores moleculares

In [10]:
df = pd.read_csv("../Limpieza_datos/Limpios/EGFR_limpio.csv")

# Visualizar datos
<hr>

In [11]:
df.head()

,Molecule ChEMBL ID,Molecule Name,Smiles,Standard Type,Standard Relation,Standard Value,Standard Units
0,CHEMBL65848,NaN,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,'=',4320.0,nM
1,CHEMBL431977,NaN,NC(=O)C1CCN(Cc2ccc(-c3cc4nccc(Nc5ccc6[nH]ccc6c...,IC50,'=',1.0,nM
2,CHEMBL78257,TYRPHOSTIN 51,N#CC(C#N)=C(N)/C(C#N)=C/c1cc(O)c(O)c(O)c1,IC50,'=',800.0,nM
3,CHEMBL69960,NaN,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,'=',170.0,nM
4,CHEMBL29197,NaN,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,IC50,'=',70.0,nM

In [13]:
df.shape

(7408, 7)

# Calcular los descriptores moleculares
<hr>

In [67]:
from rdkit import Chem
from rdkit.ML.Descriptors import MoleculeDescriptors


def calcular_descriptor(smiles):
    mol = Chem.MolFromSmiles(smiles)
    descriptors = Chem.Descriptors.CalcMolDescriptors(mol, missingVal=None, silent=True)
    return descriptors

In [68]:
df["Descriptors"] = df["Smiles"].apply(calcular_descriptor)

In [79]:
descriptors_names = list(df["Descriptors"][0].keys())

In [80]:
descriptors_names

['MaxAbsEStateIndex',
 'MaxEStateIndex',
 'MinAbsEStateIndex',
 'MinEStateIndex',
 'qed',
 'SPS',
 'MolWt',
 'HeavyAtomMolWt',
 'ExactMolWt',
 'NumValenceElectrons',
 'NumRadicalElectrons',
 'MaxPartialCharge',
 'MinPartialCharge',
 'MaxAbsPartialCharge',
 'MinAbsPartialCharge',
 'FpDensityMorgan1',
 'FpDensityMorgan2',
 'FpDensityMorgan3',
 'BCUT2D_MWHI',
 'BCUT2D_MWLOW',
 'BCUT2D_CHGHI',
 'BCUT2D_CHGLO',
 'BCUT2D_LOGPHI',
 'BCUT2D_LOGPLOW',
 'BCUT2D_MRHI',
 'BCUT2D_MRLOW',
 'AvgIpc',
 'BalabanJ',
 'BertzCT',
 'Chi0',
 'Chi0n',
 'Chi0v',
 'Chi1',
 'Chi1n',
 'Chi1v',
 'Chi2n',
 'Chi2v',
 'Chi3n',
 'Chi3v',
 'Chi4n',
 'Chi4v',
 'HallKierAlpha',
 'Ipc',
 'Kappa1',
 'Kappa2',
 'Kappa3',
 'LabuteASA',
 'PEOE_VSA1',
 'PEOE_VSA10',
 'PEOE_VSA11',
 'PEOE_VSA12',
 'PEOE_VSA13',
 'PEOE_VSA14',
 'PEOE_VSA2',
 'PEOE_VSA3',
 'PEOE_VSA4',
 'PEOE_VSA5',
 'PEOE_VSA6',
 'PEOE_VSA7',
 'PEOE_VSA8',
 'PEOE_VSA9',
 'SMR_VSA1',
 'SMR_VSA10',
 'SMR_VSA2',
 'SMR_VSA3',
 'SMR_VSA4',
 'SMR_VSA5',
 'SMR_VSA6',
 'SMR_VSA7',
 'SMR_VSA8',
 'SMR_VSA9',
 'SlogP_VSA1',
 'SlogP_VSA10',
 'SlogP_VSA11',
 'SlogP_VSA12',
 'SlogP_VSA2',
 'SlogP_VSA3',
 'SlogP_VSA4',
 'SlogP_VSA5',
 'SlogP_VSA6',
 'SlogP_VSA7',
 'SlogP_VSA8',
 'SlogP_VSA9',
 'TPSA',
 'EState_VSA1',
 'EState_VSA10',
 'EState_VSA11',
 'EState_VSA2',
 'EState_VSA3',
 'EState_VSA4',
 'EState_VSA5',
 'EState_VSA6',
 'EState_VSA7',
 'EState_VSA8',
 'EState_VSA9',
 'VSA_EState1',
 'VSA_EState10',
 'VSA_EState2',
 'VSA_EState3',
 'VSA_EState4',
 'VSA_EState5',
 'VSA_EState6',
 'VSA_EState7',
 'VSA_EState8',
 'VSA_EState9',
 'FractionCSP3',
 'HeavyAtomCount',
 'NHOHCount',
 'NOCount',
 'NumAliphaticCarbocycles',
 'NumAliphaticHeterocycles',
 'NumAliphaticRings',
 'NumAromaticCarbocycles',
 'NumAromaticHeterocycles',
 'NumAromaticRings',
 'NumHAcceptors',
 'NumHDonors',
 'NumHeteroatoms',
 'NumRotatableBonds',
 'NumSaturatedCarbocycles',
 'NumSaturatedHeterocycles',
 'NumSaturatedRings',
 'RingCount',
 'MolLogP',
 'MolMR',
 'fr_Al_COO',
 'fr_Al_OH',
 'fr_Al_OH_noTert',
 'fr_ArN',
 'fr_Ar_COO',
 'fr_Ar_N',
 'fr_Ar_NH',
 'fr_Ar_OH',
 'fr_COO',
 'fr_COO2',
 'fr_C_O',
 'fr_C_O_noCOO',
 'fr_C_S',
 'fr_HOCCN',
 'fr_Imine',
 'fr_NH0',
 'fr_NH1',
 'fr_NH2',
 'fr_N_O',
 'fr_Ndealkylation1',
 'fr_Ndealkylation2',
 'fr_Nhpyrrole',
 'fr_SH',
 'fr_aldehyde',
 'fr_alkyl_carbamate',
 'fr_alkyl_halide',
 'fr_allylic_oxid',
 'fr_amide',
 'fr_amidine',
 'fr_aniline',
 'fr_aryl_methyl',
 'fr_azide',
 'fr_azo',
 'fr_barbitur',
 'fr_benzene',
 'fr_benzodiazepine',
 'fr_bicyclic',
 'fr_diazo',
 'fr_dihydropyridine',
 'fr_epoxide',
 'fr_ester',
 'fr_ether',
 'fr_furan',
 'fr_guanido',
 'fr_halogen',
 'fr_hdrzine',
 'fr_hdrzone',
 'fr_imidazole',
 'fr_imide',
 'fr_isocyan',
 'fr_isothiocyan',
 'fr_ketone',
 'fr_ketone_Topliss',
 'fr_lactam',
 'fr_lactone',
 'fr_methoxy',
 'fr_morpholine',
 'fr_nitrile',
 'fr_nitro',
 'fr_nitro_arom',
 'fr_nitro_arom_nonortho',
 'fr_nitroso',
 'fr_oxazole',
 'fr_oxime',
 'fr_para_hydroxylation',
 'fr_phenol',
 'fr_phenol_noOrthoHbond',
 'fr_phos_acid',
 'fr_phos_ester',
 'fr_piperdine',
 'fr_piperzine',
 'fr_priamide',
 'fr_prisulfonamd',
 'fr_pyridine',
 'fr_quatN',
 'fr_sulfide',
 'fr_sulfonamd',
 'fr_sulfone',
 'fr_term_acetylene',
 'fr_tetrazole',
 'fr_thiazole',
 'fr_thiocyan',
 'fr_thiophene',
 'fr_unbrch_alkane',
 'fr_urea']

In [87]:
values_list = []

In [88]:
for i in df["Descriptors"]:
    values_list.append(list(i.values()))

In [93]:
import numpy as np
values_list_array = np.array(values_list)

In [105]:
values_list_array.shape

(7408, 210)

In [108]:
descriptors_df = pd.DataFrame(values_list_array, columns=descriptors_names)

In [109]:
descriptors_df

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,12.915017,12.915017,0.069794,-0.256890,0.504608,17.914286,470.533,444.325,470.206639,178.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,11.400854,11.400854,0.033442,-0.160264,0.282387,15.085714,481.625,454.409,481.193631,176.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,9.336538,9.336538,0.159750,-0.695453,0.352974,9.950000,268.232,260.168,268.059640,98.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,13.542332,13.542332,0.041534,-0.539617,0.489619,16.500000,482.903,462.743,482.126944,174.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.352814,5.352814,0.640826,0.640826,0.757494,10.500000,360.211,346.099,359.026939,112.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7403,11.945120,11.945120,0.342104,-0.342104,0.308512,10.833333,482.504,460.328,482.181487,180.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7404,12.551559,12.551559,0.162153,-0.162153,0.298063,15.794872,521.585,494.369,521.228771,196.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7405,12.597114,12.597114,0.070789,-0.309551,0.198115,15.700000,536.596,508.372,536.228437,202.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7406,13.067663,13.067663,0.232069,-0.487875,0.170177,12.227273,597.720,558.408,597.306353,230.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7407,13.198797,13.198797,0.238367,-0.507409,0.150655,11.113636,599.736,558.408,599.322003,232.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Crear un DataFrame con descriptores
<hr>

In [111]:
df.drop(columns=["Descriptors"], inplace=True)

In [112]:
df

,Molecule ChEMBL ID,Molecule Name,Smiles,Standard Type,Standard Relation,Standard Value,Standard Units
0,CHEMBL65848,NaN,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,'=',4320.00,nM
1,CHEMBL431977,NaN,NC(=O)C1CCN(Cc2ccc(-c3cc4nccc(Nc5ccc6[nH]ccc6c...,IC50,'=',1.00,nM
2,CHEMBL78257,TYRPHOSTIN 51,N#CC(C#N)=C(N)/C(C#N)=C/c1cc(O)c(O)c(O)c1,IC50,'=',800.00,nM
3,CHEMBL69960,NaN,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,'=',170.00,nM
4,CHEMBL29197,NaN,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,IC50,'=',70.00,nM
...,...,...,...,...,...,...,...
7403,CHEMBL5175489,NaN,C=CC(=O)Nc1cc2c(Nc3ccc(Oc4cc5nncn5cn4)c(C)c3)n...,IC50,'=',1.47,nM
7404,CHEMBL5179954,NaN,Cc1cc(Nc2ncnc3ccc(NC(=O)/C=C/[C@H]4CCCN4C)cc23...,IC50,'=',1.19,nM
7405,CHEMBL5180965,NaN,Cc1cc(Nc2ncnc3cc(O)c(NC(=O)/C=C/[C@H]4CCCN4C)c...,IC50,'=',22.75,nM
7406,CHEMBL5275712,NaN,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OCC)c(-c3cn4c5c(cccc...,IC50,'=',32.00,nM
7407,CHEMBL5266798,NaN,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(CC)c4...,IC50,'=',24.00,nM

In [115]:
descriptors_cdf = pd.concat((df, descriptors_df), axis=1)
descriptors_cdf

,Molecule ChEMBL ID,Molecule Name,Smiles,Standard Type,Standard Relation,Standard Value,Standard Units,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,CHEMBL65848,NaN,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,'=',4320.00,nM,12.915017,12.915017,0.069794,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,CHEMBL431977,NaN,NC(=O)C1CCN(Cc2ccc(-c3cc4nccc(Nc5ccc6[nH]ccc6c...,IC50,'=',1.00,nM,11.400854,11.400854,0.033442,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,CHEMBL78257,TYRPHOSTIN 51,N#CC(C#N)=C(N)/C(C#N)=C/c1cc(O)c(O)c(O)c1,IC50,'=',800.00,nM,9.336538,9.336538,0.159750,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CHEMBL69960,NaN,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,'=',170.00,nM,13.542332,13.542332,0.041534,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CHEMBL29197,NaN,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,IC50,'=',70.00,nM,5.352814,5.352814,0.640826,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7403,CHEMBL5175489,NaN,C=CC(=O)Nc1cc2c(Nc3ccc(Oc4cc5nncn5cn4)c(C)c3)n...,IC50,'=',1.47,nM,11.945120,11.945120,0.342104,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7404,CHEMBL5179954,NaN,Cc1cc(Nc2ncnc3ccc(NC(=O)/C=C/[C@H]4CCCN4C)cc23...,IC50,'=',1.19,nM,12.551559,12.551559,0.162153,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7405,CHEMBL5180965,NaN,Cc1cc(Nc2ncnc3cc(O)c(NC(=O)/C=C/[C@H]4CCCN4C)c...,IC50,'=',22.75,nM,12.597114,12.597114,0.070789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7406,CHEMBL5275712,NaN,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OCC)c(-c3cn4c5c(cccc...,IC50,'=',32.00,nM,13.067663,13.067663,0.232069,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7407,CHEMBL5266798,NaN,C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(CC)c4...,IC50,'=',24.00,nM,13.198797,13.198797,0.238367,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Guardar DataFrame
<hr>

In [116]:
descriptors_cdf.to_csv("Dataframes_descriptores/des_EGFR.csv", index=False)